name: Run PHPUnit tests

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    # Correction : Les services doivent être dans la section du job
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        ports: [3306:3306]
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4  # Version mise à jour

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, pdo, pdo_mysql
        tools: composer

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist

    # Nouvelle étape pour attendre que MySQL soit prêt
    - name: Wait for MySQL
      run: sleep 10

    - name: Run PHPUnit
    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      DB_USERNAME: ${{ secrets.MYSQL_USER }}
      DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      run: vendor/bin/phpunit